export const GET_FILM_REQUEST = "GET_FILM_REQUEST";
export const GET_FILM_SUCCESS = "GET_FILM_SUCCESS";
export const GET_FILM_ERROR = "GET_FILM_ERROR";

export const GET_PEOPLE_REQUEST = "GET_PEOPLE_REQUEST";
export const GET_PEOPLE_SUCCESS = "GET_PEOPLE_SUCCESS";
export const GET_PEOPLE_ERROR = "GET_PEOPLE_ERROR";

export const GET_PEOPLE_DETAIL_REQUEST = "GET_PEOPLE_DETAIL__REQUEST";
export const GET_PEOPLE_DETAIL_SUCCESS = "GET_PEOPLE_DETAIL__SUCCESS";
export const GET_PEOPLE_DETAIL_ERROR = "GET_PEOPLE_DETAIL_ERROR";
